name: Release
run-name: "✨ 发布正式版: (${{ github.event.head_commit.message }})"
on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  release:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if commit starts with 'v'
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%s)
          if [[ $COMMIT_MESSAGE != v* ]]; then
            echo "Commit does not start with 'v'. Skipping further steps."
            exit 1
          fi
      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18.18.2"

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            ./node_modules
          key: ${{ runner.os }}-tauri-${{ hashFiles('./pnpm-lock.yaml') }}

      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ./src-tauri/target
          key: ${{ runner.os }}-tauri-${{ hashFiles('**/Cargo.lock') }}

      - name: Install frontend dependencies
        run: pnpm install

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "HYZL-Tauri v__VERSION__"
          releaseBody: "See the assets to download and install this version."
          releaseDraft: false
          prerelease: false
